# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-09-14 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('S_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Hospitalname', models.CharField(max_length=255)),
                ('P_address', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name', models.CharField(max_length=255)),
                ('access', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('hash_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reg_Requests',
            fields=[
                ('S_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Hospitalname', models.CharField(max_length=255)),
                ('P_address', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
            ],
        ),
    ]
