# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-09-14 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkeeper_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reg_Requests',
            new_name='Requests',
        ),
    ]
