# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-09-14 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkeeper_app', '0003_auto_20230914_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests1',
            new_name='Requests',
        ),
    ]
